# DBSCAN Clustering

## Import data

This data comprises of the top three principal components obtained during PCA with a radial basis function kernel, which together contain ~95% of the total variance of the original dataset (as seen in the cumulative variance barplot from the PCA section).

In [10]:
import pandas as pd

df = pd.read_csv('../../data/kpca3d.csv')
df.head()

,PC1,PC2,PC3,All Time Rank,All Time Rank Bin,Track,Artist
0,0.150251,0.630721,-0.248971,1,1,MILLION DOLLAR BABY,Tommy Richman
1,-0.089829,-0.025684,-0.041813,2,1,Not Like Us,Kendrick Lamar
2,-0.021122,0.281381,-0.197222,3,1,i like the way you kiss me,Artemas
3,0.600836,0.611817,-0.103087,4,1,Flowers,Miley Cyrus
4,0.010005,0.400341,-0.205579,6,1,Lovin On Me,Jack Harlow

## Separate label and principal components

In [11]:
# extract label
label = df[['All Time Rank Bin']]

# extract three principal components
df_pca = df[['PC1', 'PC2', 'PC3']].values
pd.DataFrame(df_pca).head()

          0         1         2
0  0.150251  0.630721 -0.248971
1 -0.089829 -0.025684 -0.041813
2 -0.021122  0.281381 -0.197222
3  0.600836  0.611817 -0.103087
4  0.010005  0.400341 -0.205579

## Visualize DBSCAN clusters with eps=[0.05, 0.10, 0.15], min_samples=50

In [ ]:
import plotly.graph_objects as go
from sklearn.cluster import DBSCAN

def visualize_clusters_3d_dbscan(X, eps_values, min_samples):
    """Create 3D scatterplots to visualize clustering with DBSCAN."""
    
    for eps in eps_values:
        labels = DBSCAN(eps=eps, min_samples=min_samples).fit_predict(X)
        
        # in this case, noise points are actually the group with All Time Rank Bin = 1, so assign green
        # the only other cluster is the group with All Time Rank Bin = 0, so assign green
        cluster_colors = ['mediumseagreen' if label == -1 else 'black' for label in labels]
        
        # data points
        fig_3d = go.Figure(data=go.Scatter3d(
            x=X[:, 0], y=X[:, 1], z=X[:, 2],
            mode='markers',
            marker=dict(size=2.5, color=cluster_colors, opacity=0.5),
            name='Data Points'
        ))

        title = f'3D Clustered PCA Data (DBSCAN eps={eps} min_samples={min_samples})'
        fig_3d.update_layout(
            title=title,
            scene=dict(xaxis_title='PC1', yaxis_title='PC2', zaxis_title='PC3'),
            margin=dict(l=0, r=0, b=0, t=40),
            scene_camera=dict(
                eye=dict(x=1.3, y=-1.7, z=1.3), 
                center=dict(x=0, y=0, z=0), 
                up=dict(x=0, y=0, z=1)
            ),
            autosize=False, 
            width=1000, 
            height=800
        )

        # save Plotly's HTML files to display on a website
        fig_3d.write_html(f"./dbscan-plots/{title.replace(' ', '')}.html")
        fig_3d.show()
            
eps_values = [0.05, 0.10, 0.15]
min_samples = 50
visualize_clusters_3d_dbscan(df_pca, eps_values, min_samples)